### ISSUE TITLE
Formatter adds additional space around forward slash (/)

### ISSUE THREAD

**Issue by mbush92** [ahernguo/urscript-extension#1]
When saving the file and the formatting takes place extra spaces are added around the forward slash sign, this is used in RPC addresses and other HTML addresses and causes issues when downloaded to the robot to run as it cannot handle the extra spaces

`"http://10.0.2.2:8438/RPC2"` becomes `"http: /  / 10.0.2.2:8438 / RPC2"`

**Comment by ahernguo** [comment]
Oh, I miss this condition. Thanks for fix this.

**Comment by mbush92** [comment]
We are running against the master commit now and everything looks really good but I did find one use case that still results in a bad format.  `-4.4E-4` becomes `- 4.4E - 4`
 upon saving the code.  I tried converting it into the correct decimal number and it appears because the number is preceded by a `[` that is causing format issues as well as the number `p[ -0.00044,...` becomes `p[ - 0.00044, ...` 

Everything else appears to be good.

**Comment by mbush92** [comment]
There are also issues if you have more than 1 negative number in a line. `p[ - 0.00044, -0.00419, 0.42121, - 0.78, 0.0, 0.0]` you can see the Y value is negated correctly but the value in the RX position has a space.  I tested this with another list and if it contains more than one negated number in the list all subsequent numbers have a space inserted.

**Comment by ahernguo** [comment]
Oh, I missed it. 🤣

I push new commit to fix it. Maybe you can try latest `master`.

Thanks for your report.

**Comment by mbush92** [comment]
@ahernguo Sorry I forgot to respond after we tested, I am currently running master in our production environment.  Seems all issues we have identified that were stopping us from using it have been addressed.
