### ISSUE TITLE
String or comment containing `end` cause an indant decrease

### ISSUE THREAD

**Issue by Yuki-cpp** [ahernguo/urscript-extension#12]
Hello
When using this extension (v0.1.7, installed from the extension menu on vscode 1.55.2 on Ubuntu 18.04)  the formatter reduces the indentation level when it encounter a `end` in a string or an inline comment.

Consider the following MWE :
```python
def foo(str):
end

if true:
    foo("abc")
    foo("end")
end

if true:
    foo("abc")
    foo("abc") # do not use end but reduce indent anyway
    foo("abc")
end

if true:
    foo("abc")
    # do not use end but reduce indent anyway
    foo("abc")
end
```

Using the v0.1.7 release, the above snippet would be formatted as:
```python
def foo(str):
end

if true:
    foo("abc")
foo("end")
foo("abc")
end

if true:
    foo("abc")
foo("abc") # do not use end but reduce indent anyway
end

if true:
    foo("abc")
    # do not use end but do not reduce indent
    foo("abc")
end
```
Note that when a string or inline comment comment contains `end` the current line and the following ones are missing one indent level. Non inline comments are unaffected

I believe that the culprit is the following line line as it doesn't seem to filter out end in inline comments or strings but i might be mistaken.

https://github.com/ahernguo/urscript-extension/blob/8025b20a2ea8e35a670b86a51320d9936d76fd87/src/features/formattingEditProvider.ts#L491 

Cheers

**Comment by ahernguo** [comment]
Thanks for your report 😀 The root cause is the regex pattern without filter inline comment as you found. That's my mistake 😅

So I make a new regex to ensure `end` `elif` `else` is start of the line. Both of `needIncreaseIndent` and `needDecreaseIndent` are fixed.

I push the v0.1.8 and hope it can solve the error 😊

**Comment by Yuki-cpp** [comment]
Works like a charm.
Thanks a lot for the quick fix :+1:
