### ISSUE TITLE
configurable IO functions lexer error

### ISSUE THREAD

**Issue by robot-ranger** [ahernguo/urscript-extension#16]
any function with the word "configurable" in the name uses an inappropriate character "ﬁ" (single character) instead of "f" and "i" individually. this results in a lexer error on the UR robots.

functions that I have found affected:
set_configurable_digital_in()
set_configurable_digital_out()
get_configurable_digital_in()
get_configurable_digital_out()

bad function call generated by extension completion:
get_conﬁgurable_digital_in()
(note that the "ﬁ" is one character)

good function call typed out manually:
get_configurable_digital_in()

I think anything with the word "configurable" is affected, but I cannot say for certain.

function called from extension completion, results in "lexer error" in polyscope:
![before](https://user-images.githubusercontent.com/93950632/146654610-8c2a6310-78d1-419f-83dc-db0fc6623d29.png)

function if typed out manually, compiles and runs fine on polyscope:
![after](https://user-images.githubusercontent.com/93950632/146654622-567eb7f2-8376-469c-8f34-ec76aa7c7946.png)

**Comment by robot-ranger** [comment]
I am not sure if this is related, but it appears that even the hover tip & color theme recognizes the incongruity in the characters by changing the color of the text in the hover tip:
![function_tip](https://user-images.githubusercontent.com/93950632/146654737-46af21a3-b6ef-4fa0-9578-25863ed793db.png)

**Comment by ahernguo** [comment]
Oh, that a misspelling in `functions.json`.

I copied the function from official PDF, but I didn't check the spell. 🤣

I push the latest version v0.1.9, it should be solved.

**Comment by robot-ranger** [comment]
I just installed v0.1.9 - error is gone! Thank you! Very frustrating to find that error in the field. I appreciate the quick fix.
