### ISSUE TITLE
end -autocompletion

### ISSUE THREAD

**Issue by FrRacz** [ahernguo/urscript-extension#20]
Hi I've got the ongoing issue when writing for example:
if expression:
   do sth.
end -> when i type end i get autocompletion for end_force_mode, end_freedrive_mode etc.
It would be nice if the simple 'end'-Statement would be an option with high priority so i don't always have to hit esc when typing end.

Cheers

**Comment by ahernguo** [comment]
sorry for the late reply. I've been too busy the last few months 😣

I add the `end` keyword to `CompletionList` and release v0.1.10. 

Thanks for your advice 😄
