### ISSUE TITLE
Incorrect signature in tooltip for params with default values

### ISSUE THREAD

**Issue by agmlego** [ahernguo/urscript-extension#22]
With functions defined with default values for parameters, the extension generates incorrect signature for the tool tips.

For example, the function declaration here:
```
###
# Wait for an input signal to change state on a Modbus/TCP server
# @param input string the name of the created signal to use as an input
# @param timeout_delay float seconds to wait for signal before return, default 4.0
# @param invert_input bool whether to watch for a falling edge, default False
# @returns bool whether the signal succeeded or timed out
###
def modbus_wait(input, timeout_delay = 4.0, invert_input = False):
```
I would expect this to output a signature like this `bool modbus_wait(string input, float timeout_delay, bool invert_input)` or like this `bool modbus_wait(string input, float timeout_delay=4.0, bool invert_input=False)` .

Instead, I get: `bool modbus_wait(input, timeout_delay = 4.0, invert_input(string input, float timeout_delay, bool invert_input)`

**Comment by ahernguo** [comment]
I fix this problem on v0.1.12. you can try this version and send a feed back if error still occurred. 

It cause by a incorrect regex to catch method name. I almost not use optional parameter, so I didn't test that before. Thanks for your report 😄
