### ISSUE TITLE
Parameter comments are not shown in tooltips

### ISSUE THREAD

**Issue by agmlego** [ahernguo/urscript-extension#23]
For the function declaration:
```
###
# Wait for an input signal to change state on a Modbus/TCP server
# @param input string the name of the created signal to use as an input
# @param timeout_delay float seconds to wait for signal before return, default 4.0
# @param invert_input bool whether to watch for a falling edge, default False
# @returns bool whether the signal succeeded or timed out
###
def modbus_wait(input, timeout_delay = 4.0, invert_input = False):
```

I would expect the tool tip to show the comments for the params like the following:

> Wait for an input signal to change state on a Modbus/TCP server
> 
> - _Parameters_
>   * input (string): the name of the created signal to use as an input
>   * timeout_delay (float): seconds to wait for signal before return, default 4.0
>   * invert_input (bool): whether to watch for a falling edge, default False
> 
> - _Return_
>     whether the signal succeeded or timed out

Instead, the extension produces this:

> Wait for an input signal to change state on a Modbus/TCP server
> 
> - _Return_
>     whether the signal succeeded or timed out

**Comment by ahernguo** [comment]
I release the version v0.1.12 to add this feature.

In early stage, I want to keep tooltip cleanly and I make signature for more information. But back to present, I agree you idea for display details on tooltip 😄
