### ISSUE TITLE
Missing LICENSE file

### ISSUE THREAD

**Issue by thor2304** [ahernguo/urscript-extension#27]
Hi,
I really appreciate your project, and would like to use your TextMate grammar, for a project visualizing some URscript code (It is a research project, so i need to have icenses in order).

I tried finding out what license this project is under, to determine whether i would be allowed, but was unsuccesful.

If you add a `LICENSE.md` file to the root of the repository, GitHub will show the license automatically.
See these links:
[https://github.blog/2016-09-21-license-now-displayed-on-repository-overview/](https://github.blog/2016-09-21-license-now-displayed-on-repository-overview/)

[https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository)

Thank you for the awesome tool, and may you have a good day.

**Comment by ahernguo** [comment]
Oh, I forgot I had add the MIT license last week.    Thanks for your  advice 😄
