### ISSUE TITLE
Formatting changes on each save for some lines

### ISSUE THREAD

**Issue by mbush92** [ahernguo/urscript-extension#6]
We have an issue where code such as `if (not isArcOn()):` will change with each save, it will go from the original code to `if ( not isArcOn())` on the next save it goes back to the original code.  There are other formatting changes that do this is well but this is the one that I keep seeing over and over in our PR's on the code because it vacillates with each save of the file.

I have tested this with the latest 0.1.2 code release and the issue is still there.

**Comment by ahernguo** [comment]
Hi @mbush92 ,
  I'm trying to fix this problem on 00fca1c @ master or release v0.1.3. maybe you can take a try.

**Comment by mbush92** [comment]
That fixed the issue.  Thanks!  Do you plan on releasing this to the VSCode extension store?

**Comment by ahernguo** [comment]
That's a good idea 😁 I will release it when I have free time ...
