### ISSUE TITLE
Key word highlighting when used in variable or function name

### ISSUE THREAD

**Issue by mbush92** [ahernguo/urscript-extension#7]
When using a UR keyword in a function, thread or variable name the formatter still formats the word as if it were being used as a keyword.  Desired behavior is that keywords are ignored unless they are used as standalone words with a space preceding and following the word.

Examples:

<img width="339" alt="image" src="https://user-images.githubusercontent.com/15862774/72823927-0ea9cc00-3c3a-11ea-8e17-b8459bae3ff8.png">

<img width="162" alt="image" src="https://user-images.githubusercontent.com/15862774/72824007-313be500-3c3a-11ea-9488-231eafeb5609.png">

**Comment by ahernguo** [comment]
I typed the keyword that you shown in picture. But it didn't format as a keyword.

![try_it](https://user-images.githubusercontent.com/53938337/73054427-5d1ecb00-3ec5-11ea-831a-6c5dbe7e901f.png)

Are you use the latest version on extension store? Or what version you installed?

**Comment by mbush92** [comment]
I’m running 0.1.4 which is the latest version according to the extension store. 

Let me try reloading it again today to see if that fixes the issue. 

Thanks,

Matthew Bush
Hirebotics 
M: ‭(615) 479-6151‬

**Comment by mbush92** [comment]
I found that I had another formatter for URScript that even though disabled must have been causing the format issue we were seeing, after I removed it, formatting worked as desired.
