### ISSUE TITLE
Go To Definition not working

### ISSUE THREAD

**Issue by mbush92** [ahernguo/urscript-extension#9]
I see in the README file that we are supposed to be able to right click on a function call and then go to the definition of that function.  When I do that I get the following `No Definition Found for <insert function name>`. Is there a setting we need to turn on somewhere or is this a bug? 

Version: 1.45.0
Commit: d69a79b73808559a91206d73d7717ff5f798f23c
Date: 2020-05-07T15:57:33.467Z (6 days ago)
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0.45

Extension version 0.1.5

**Comment by ahernguo** [comment]
The feature was worked successfully in my code.

May you post some parts of your code that trigger `No Definition Found for` ? I think the regex pattern something wrong with some case.

**Comment by mbush92** [comment]
I created a sample repo at https://github.com/mbush92/urscript-test with various sample functions.  The only definition or peek function I can make work is when the definition and usage of the function are in the same file, check out the `add2Numbers()` function, you can go to the definition in the file where it is defined, but not from the file beside it.  

We have our code structured in folders like the examples in this.  We often define the functions in one folder and then we are using them in another folder.

Here is what I see when I try to go to the definition or use the peek function

![image](https://user-images.githubusercontent.com/15862774/82231293-935bdc80-98f2-11ea-98ee-cef5a732d882.png)

But if its defined in the same file I get this:

![image](https://user-images.githubusercontent.com/15862774/82231368-acfd2400-98f2-11ea-88fa-8aa39316d74c.png)


I have the following extensions installed in this workspace

![image](https://user-images.githubusercontent.com/15862774/82231199-6e676980-98f2-11ea-9bcf-4ec941856abb.png)

**Comment by ahernguo** [comment]
Hi @mbush92 ,

I have update v0.1.6, please update and try again 😄

The problem is ...

```ts
fs.readdirSync(workspace.uri.fsPath)
```

only get files in `workspace.uri.fsPath` (without subfolders). so I add a new function `getAllFiles` to search all files.

BTW, `Go to definition` and `Hover` only works when you use **`Open Folder...`** or **`Open Workspace...`**. The search will failed when use **`Open File...`** because `workspace.uri.fsPath` will be `null`.

- Search failed when **`Open File...`**
    ![image](https://user-images.githubusercontent.com/53938337/82295916-017fcc80-99e3-11ea-98c8-45071c851c5f.png)

- Search successfully when **`Open Folder...`**
![image](https://user-images.githubusercontent.com/53938337/82296044-2d02b700-99e3-11ea-8c1e-4f7b8ae6109f.png)

**Comment by mbush92** [comment]
Thanks for the update, this is still not working for me.  I have disabled all other extensions and have tried opening as both a folder and a named workspace.  The one difference I can see is I am running a Mac and it appears you are running windows.

I will try to take a look at this as well and see if I can find any issues that would cause it to work on Windows and fail on Mac

**Comment by ahernguo** [comment]
Oh, that's really strange 😨
I will try to get a Mac OS virtual machine and try this issue on it when I have free time this weekend.

**Comment by mbush92** [comment]
@ahernguo I was able to get VSCode installed on a Windows machine that I have (Mac running bootcamp) and I can say that this feature is working on Windows.  Man it sure is handy!  Have you had any luck figuring out what is going on with Mac?

Now that I know that it works I may try to poke around the code and see if I can find anything that would cause it not to work on Mac when I get a little free-time

**Comment by mbush92** [comment]
Great NEWS!  I got it working.  I was able to finally find a message on the log(window) for the output tab on the terminal and noticed that there was an issue with a directory with a symboilic link

![image](https://user-images.githubusercontent.com/15862774/83431433-f1adb280-a3fc-11ea-93ec-bbe6424b7d59.png)

This directory did not even show up in VSCode but when I went to my file finder you could see there was a directory there and the link had been broken.  I deleted the directory and viola it all started working!!

Going to close this out now.

**Comment by ahernguo** [comment]
OK, that's really a good news 😁
